### PR TITLE
4 overview all

### PR DESCRIPTION
**Pull request by BenBerkenbosch**
Request Review

### CODE REVIEW

**Comment by keygun-development** [comment]
Missing complete backend

**Comment by keygun-development** [comment]
Style is not what it has got to be

**Comment by keygun-development** [comment]
Still not respecting the requested changes

**Comment by GijsPampiermole** [comment]
Drop this. Has already been resolved in different branches/issue's
[HTML Issue](https://github.com/GijsPampiermole/Actievadis/issues/33) [Html Branch](https://github.com/GijsPampiermole/Actievadis/tree/33-html-activity-overview)
[PHP Issue](https://github.com/GijsPampiermole/Actievadis/issues/34) **already merged**

**Pull request closed without merging**
